### ISSUE TITLE
桌面版能新增自動備份字幕檔的功能嗎?

### ISSUE THREAD

**Issue by JJININDER** [Fanhuaji/discussion#31]
字幕檔本身檔案不大，但要建立挺耗時的。
今天一次將十幾個字幕檔給桌面版的繁化姬做轉換，結果剛好遇到電腦無預警自動重開機；
準備重新再轉換一次字幕檔時，發現十幾個字幕檔全部變成0KB，打開文件全是空白的。
估計是電腦無預警重開機，造成要轉換的所有檔案全部損毀，後悔字幕檔沒做備份。
不知繁化姬本身有無自動備份要轉換的檔案功能嗎?

**Comment by jfcherng** [comment]
這個算是 https://github.com/James1201/Fanhuaji-GUI-Release/releases 的問題。不過該程式停止維護。
