### ISSUE TITLE
中国化：着字用法修正

### ISSUE THREAD

**Issue by zjns** [Fanhuaji/discussion#34]
简中语境中，以下词语都没有**著**字用法，应该用**着**。
執著 -> 执着
顧著 -> 顾着
吵著 -> 吵着
棋高一著 -> 棋高一着
高人一著 -> 高人一着
棋差一著 -> 棋差一着
棋輸一著 -> 棋输一着
歪打正著 -> 歪打正着
眼瞅著 -> 眼瞅着
搆得到 -> 够得着
搆不到 -> 够不着

**Comment by zjns** [comment]
补充：
等著 -> 等着

**Comment by zjns** [comment]
补充2：
混著 -> 混着

**Comment by zjns** [comment]
补充3：
慢著 -> 慢着
輪著 -> 轮着

**Comment by n6333373** [comment]
感謝回報！
