### ISSUE TITLE
關於轉換檔案的大小限制

### ISSUE THREAD

**Issue by kenglly** [Fanhuaji/discussion#36]
我在使用桌面板轉換遊戲文本時，遇到檔案過大(11MB)而無法轉換的問題。

想請問本軟體支援的檔案上限是多少？是否可能再支援較大檔案的轉換？

謝謝！

**Comment by n6333373** [comment]
已更改設定，您再試試看桌面版用 10MB 切割看看。

**Comment by kenglly** [comment]
非常感謝你們用心的維護+修正～

    在 2022年6月20日 星期一 下午11:58:57 [GMT+8]， ***@***.***> 寫道：  
 
 


已更改設定，您再試試看桌面版用 10MB 切割看看。

**Comment by n6333373** [comment]
assuming resolved.
