### ISSUE TITLE
[BUG?]  在web端输入包含 “桜” 字 出现 伺服器連線錯誤

### ISSUE THREAD

**Issue by ghost** [Fanhuaji/discussion#38]
如下图所示，任何模式转换均提示 伺服器連線錯誤
麻烦大佬排查一下，谢谢。
![image](https://user-images.githubusercontent.com/19740260/211155928-f95ec9b6-ef0e-4b6c-b6aa-3848fd2c2d21.png)
![image](https://user-images.githubusercontent.com/19740260/211155960-abf596d6-8243-4840-8b83-92e8731a142a.png)

**Comment by jfcherng** [comment]
感謝回報，已解決。

**Comment by Akatmks** [comment]
大概是從今天 08:00 - 09:00 (UTC) 開始有這個問題的。只要轉換文字包含日語，不論是日語漢字還是假名，都會出現伺服器連線錯誤的提示。API 則會返回 502 Bad Gateway。
