### ISSUE TITLE
Consider open source for self hosting?

### ISSUE THREAD

**Issue by beenotung** [Fanhuaji/discussion#42]
This software is currently available via HTTP API for free, would the author consider to release the software via github/npm/pipy, so we can self host the translate service?

And what is the system requirement (disk space and memory consumption) for self hosting the translation service?

**Comment by jfcherng** [comment]
No. It was intentionally closed-source.

**Comment by beenotung** [comment]
Thanks for the clarification, and appreciate the free API access
