### ISSUE TITLE
Mtool 文本繁化到日文原文導致翻譯失效

### ISSUE THREAD

**Issue by paul0728** [Fanhuaji/discussion#45]
我在使用mtool取出的遊戲文本進行繁化時，會產生"繁化到日文原文部分而導致原文改變，翻譯失效"的情形。請問是有辦法進行設置而避免的嗎?謝謝

**Comment by jfcherng** [comment]
有實際例子嗎？如果是任意情況都會，那麼請給出任意情況的「實際例子」。

**Comment by paul0728** [comment]
> 有實際例子嗎？如果是任意情況都會，那麼請給出任意情況的「實際例子」。
[Sakura14B翻译文件_別人翻的.json](https://github.com/user-attachments/files/18136194/Sakura14B._.json)


這個遊戲文本當中第3985行中

    "我々新SAO開発チームはSAO事件の後、あのような凄惨な事件を再発させてしまう事がないように重大さを真摯に受け止め検討を重ねてまいりました。": "我们新SAO开发小组在SAO事件之后、为了不让那种凄惨的事件再次发生而真挚地接受教训并且不断检讨。",


繁化姬會把原文中的 "凄" 轉成 "淒" 而導致原文改變
不過日文中有許多跟中文一樣的漢字
我想大概是不是沒辦法分別?
但只是在想是不是可以透過"自訂取代"來避免誤繁化
![image](https://github.com/user-attachments/assets/734f01bf-63c6-42f0-a4bf-8baabdc86dc2)
但一時還不會用

**Comment by jfcherng** [comment]
初步可以重現問題，再找時間研究看能不能解決。

該 GUI 程式不是我寫的且很久沒更新了，網頁版有對日文處理的相關選項，但目前看來有您提出的「淒」的問題。不過嘛...「凄」也是對的而且似乎更常用。

**Comment by paul0728** [comment]
> 初步可以重現問題，再找時間研究看能不能解決。
> 
> 該 GUI 程式不是我寫的且很久沒更新了，網頁版有對日文處理的相關選項，但目前看來有您提出的「淒」的問題。不過嘛...「凄」也是對的而且似乎更常用。

請教一下以這個例子而言，網頁版該如何設定避免繁化到前面原文
![image](https://github.com/user-attachments/assets/5035c102-d4af-48b9-89d2-f807b946a519)

**Comment by jfcherng** [comment]
> 請教一下以這個例子而言，網頁版該如何設定避免繁化到前面原文 

請給出實際可以重現且能複製的例子，要我自己去 OCR 圖片那是不可能的，我寧願就把 issue 這麼放著。

**Comment by GameProgram777** [comment]
> > 請教一下以這個例子而言，網頁版該如何設定避免繁化到前面原文
> 
> 請給出實際可以重現且能複製的例子，要我自己去 OCR 圖片那是不可能的，我寧願就把 issue 這麼放著。

用手機不小心用到另一個帳號留言（我是 @paul0728 ）

抱歉沒表達清楚
例子就是一樣我上面舉的例子喔
檔案也是我上面提供的那個檔案結構
{
原文：譯文
}

該如何使繁化姬略過整個檔案中所有原文部分？

**Comment by jfcherng** [comment]
此類客製需求應由使用者自己寫程式完成

**Comment by paul0728** [comment]
> 此類客製需求應由使用者自己寫程式完成

不好意思，我資質愚鈍，看完了全部文檔還是無法解決，懇請您不吝教學。

Mtool資料格式是這樣:

{
原文1(可能日文或英文) : 中文1,
原文2(可能日文或英文) : 中文2,
原文3(可能日文或英文) : 中文3

}


我做了以下嘗試都沒有改善:
1. 將"一般日文的處理策略"以及"日文樣式的處理策略"都調整成"保護"，結果"凄"還是被轉成"淒"，原文的部分還是被繁化了。
2. 自訂日文樣式
我對.ASS格式不是非常熟悉，尋求chatgpt4o 建議，他建議將原文包成
"{\\v4_style:Default}我々新SAO開発チームはSAO事件の後、あのような凄惨な事件を再発させてしまう事がないように重大さを真摯に受け止め検討を重ねてまいりました。{\\v4_style_end}"
以及
"[v4_style:ignore]我々新SAO開発チームはSAO事件の後、あのような凄惨な事件を再発させてしまう事がないように重大さを真摯に受け止め検討を重ねてまいりました。[/v4_style]"

並在"日文樣式"以及"不要處理的樣式"都打上上述標籤，但"凄"還是被轉成"淒"。

所以想請教該如何設置才行?還是目前無法處理這種情況?謝謝

**Comment by jfcherng** [comment]
"凄淒" 的問題是我該解決的。其餘的問題是您該解決的。

**Comment by paul0728** [comment]
> > 此類客製需求應由使用者自己寫程式完成
> 
> 不好意思，我資質愚鈍，看完了全部文檔還是無法解決，懇請您不吝教學。
> 
> Mtool資料格式是這樣:
> 
> { 原文1(可能日文或英文) : 中文1, 原文2(可能日文或英文) : 中文2, 原文3(可能日文或英文) : 中文3
> 
> }
> 
> 我做了以下嘗試都沒有改善:
> 
> 1. 將"一般日文的處理策略"以及"日文樣式的處理策略"都調整成"保護"，結果"凄"還是被轉成"淒"，原文的部分還是被繁化了。
> 2. 自訂日文樣式
>    我對.ASS格式不是非常熟悉，尋求chatgpt4o 建議，他建議將原文包成
>    "{\v4_style:Default}我々新SAO開発チームはSAO事件の後、あのような凄惨な事件を再発させてしまう事がないように重大さを真摯に受け止め検討を重ねてまいりました。{\v4_style_end}"
>    以及
>    "[v4_style:ignore]我々新SAO開発チームはSAO事件の後、あのような凄惨な事件を再発させてしまう事がないように重大さを真摯に受け止め検討を重ねてまいりました。[/v4_style]"
> 
> 並在"日文樣式"以及"不要處理的樣式"都打上上述標籤，但"凄"還是被轉成"淒"。
> 
> 所以想請教該如何設置才行?還是目前無法處理這種情況?謝謝

"凄"之所以被轉成"淒"，代表我沒有成功設定使其識別原文區域，但我照上述設定都無法使其識別。只要能成功識別正確區域，"凄"的問題也就解決了

**Comment by jfcherng** [comment]
> "凄"之所以被轉成"淒"，代表我沒有成功設定使其識別原文區域，但我照上述設定都無法使其識別。只要能成功識別正確區域，"凄"的問題也就解決了

這是我這邊程式的問題，與您無關。

**Comment by paul0728** [comment]
> > "凄"之所以被轉成"淒"，代表我沒有成功設定使其識別原文區域，但我照上述設定都無法使其識別。只要能成功識別正確區域，"凄"的問題也就解決了
> 
> 這是我這邊程式的問題，與您無關。

原來如此，那我了解了，謝謝!

**Comment by jfcherng** [comment]
"凄淒" 的問題已解決。

**Comment by paul0728** [comment]
> "凄淒" 的問題已解決。

好迅速!!謝謝!!
不過網站好像暫時無法使用了
