### ISSUE TITLE
Mtool 大文本繁化結果為空

### ISSUE THREAD

**Issue by paul0728** [Fanhuaji/discussion#46]
我將mtool提取之文本丟進繁化姬，發現檔案文本量大到某個程度，輸出就會為空。
舉例來說這個檔案:
[Sakura14B翻译文件_別人翻的.json](https://github.com/user-attachments/files/18136217/Sakura14B._.json)
丟進繁化姬以後會得到以下之空檔案:
[Sakura14B翻译文件_別人翻的 (1).json](https://github.com/user-attachments/files/18136218/Sakura14B._.1.json)

我嘗試進行分割可以解決問題，但這問題如果繁化姬能有自己的判斷機制就更好了
以下提供我的json分割/合成/檢查資料夾中空檔案之程式碼:

[json_split.txt](https://github.com/user-attachments/files/18136225/json_split.txt)
[json_merge.txt](https://github.com/user-attachments/files/18136226/json_merge.txt)
[json_blank_check.txt](https://github.com/user-attachments/files/18136227/json_blank_check.txt)

**Comment by jfcherng** [comment]
> 但這問題如果繁化姬能有自己的判斷機制就更好了

應該不會有，畢竟這是我自己設下的限制。

**Comment by paul0728** [comment]
> > 但這問題如果繁化姬能有自己的判斷機制就更好了
> 
> 應該不會有，畢竟這是我自己設下的限制。


了解，不過好奇為何不開放限制?這樣其實不是很方便，我翻譯的遊戲其實也只是很小的遊戲，那個文本量也沒多少，就要把文本分成好幾分，蠻麻煩的。寫個判斷式，大到某個程度自動拆分翻譯不就解決了嗎?網頁版遊戲是server端進行有流量限制到可以理解，本地端(app)應該開放比較好吧?

**Comment by jfcherng** [comment]
> 了解，不過好奇為何不開放限制?這樣其實不是很方便，我翻譯的遊戲其實也只是很小的遊戲，那個文本量也沒多少，就要把文本分成好幾分。寫個判斷式，大到某個程度自動拆分翻譯不就解決了嗎?

不為什麼，您想做公益您自己寫一個。

**Comment by jfcherng** [comment]
> 本地端(app)應該開放比較好吧?

我從來沒寫過這種東西。所有聲稱使用繁化姬的本地程式都只是使用繁化姬伺服器提供的 API 。

**Comment by paul0728** [comment]
> > 了解，不過好奇為何不開放限制?這樣其實不是很方便，我翻譯的遊戲其實也只是很小的遊戲，那個文本量也沒多少，就要把文本分成好幾分。寫個判斷式，大到某個程度自動拆分翻譯不就解決了嗎?
> 
> 不為什麼，您想做公益您自己寫一個。

可以，如果您願意提供源碼，我有時間可以研究，並加上拆分功能

**Comment by paul0728** [comment]
> > 本地端(app)應該開放比較好吧?
> 
> 我從來沒寫過這種東西。所有聲稱使用繁化姬的本地程式都只是使用繁化姬伺服器提供的 API 。


原來，了解

**Comment by jfcherng** [comment]
> 可以，如果您願意提供源碼，我有時間可以研究，並加上拆分功能

所有我想公開的東西都已經公開了。沒放上來的就是不想公開。

**Comment by paul0728** [comment]
> > 可以，如果您願意提供源碼，我有時間可以研究，並加上拆分功能
> 
> 所有我想公開的東西都已經公開了。沒放上來的就是不想公開。

了解
